### ISSUE TITLE
form extra class - add axllent/silverstripe-bootstrap-forms

### ISSUE THREAD

**Issue by korthjp17** [dynamic/silverstripe-base-site#22]
Since BS-Forms hasn't been updated for SS4 yet, would it be possible to do something similar to what he's doing as an extension?

The main thing that we need is the `.form-control` class added to the input fields.

I think this is how UC was doing it:
https://github.com/unclecheese/silverstripe-bootstrap-forms/blob/8ecd2d075b75de100de6828fc441303749e0c6d4/code/BootstrapFormField.php#L252-L266

and

https://github.com/unclecheese/silverstripe-bootstrap-forms/blob/05e7829c895deed54e8281d4129f71985ae73fd1/code/BootstrapTextField.php#L21

**Comment by muskie9** [comment]
Is this still valid?
