### ISSUE TITLE
allow divs to be included in WYSIWYG editor

### ISSUE THREAD

**Issue by korthjp17** [dynamic/silverstripe-base-site#73]
The CMSTweaks module is currently setting divs as invalid elements in the onAfterInit, so we need a way to override this.

https://github.com/axllent/silverstripe-cms-tweaks/blob/66de39757db93bb1988195e7a2c1e5b5ea3f7e5d/src/CMSTweaks.php#L81-L87

**Comment by jsirish** [comment]
Did we ever find a way to do this?

**Comment by muskie9** [comment]
The module has been updated to run off of config values: https://github.com/axllent/silverstripe-cms-tweaks/blob/master/src/CMSTweaks.php#L123-L125

**Comment by muskie9** [comment]
Pulling in `2.0.2` should allow configuring the allowed/disallowed elements

**Comment by korthjp17** [comment]
I drop this into some projects as we need it: https://github.com/sargentofoods/FSI/blob/master/app/_config/mysite.yml#L22-L24
